[tool.pyright]
reportAny = false
reportExplicitAny = false
reportDeprecated = false
reportImplicitOverride = false
reportUntypedNamedTuple = false
reportMissingModuleSource = "none"
reportUnnecessaryTypeIgnoreComment = "error"
